name: CICD

on:
  push:
    branches: [ main ]
jobs:  
  run-k8d:
    name: Create k3d cluster and deploy app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: AbsaOSS/k3d-action@v2
        name: "Create single k3d Cluster with imported Registry"
        with:
          cluster-name: CICD-test-cluster
          args: >-
            --agents 3
            --no-lb
            --k3s-arg "--no-deploy=traefik,servicelb,metrics-server@server:*"
      - name: "Docker repo demo"
        run: |
            helm install demo-gh-actions ./helm 
